version: "3"

services:
  bff:
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    ports:
      - "8080:80"
    environment:
      Frontend__ExternalApiUrl: "http://external-api:9090/"
  external-api:
    build:
      context: .
      dockerfile: ./ExternalApi/Dockerfile
    ports:
      - "9090:80"

